### ISSUE TITLE
Task2

### ISSUE THREAD

**Issue by Shtramak** [Shtramak/BOS_Collections#1]
Кожний створює свою гілку, у якій пише тести до наступних методів:
Shtramak : clear, size, isEmpty, iterator, contains
Victor : remove(T), toArray, get, set
Yura : add, remove(int), indexOf, add(int, T)
Після цього кожен замержить до своєї гілки методи реалізовані іншими.
Коли всі все зробимо - замержимо всі зміни у гілку мастер

**Comment by Nebozavr** [comment]
Гілку створив, тетси реалізовані, в очікуванні від інших учасників, дозволу на мерж...
